# Generated by Django 5.2.8 on 2025-12-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0004_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeentry',
            options={'ordering': ['order', '-id']},
        ),
        migrations.AddField(
            model_name='resumeentry',
            name='order',
            field=models.IntegerField(default=0, help_text='Ordering for resume items; lower appear first'),
        ),
    ]
